### ISSUE TITLE
Don't remove the copyright declaration from the codes

### ISSUE THREAD

**Issue by WillemJiang** [NotepadFree/NotepadFree#11]
You have the right to fork the project, but you don't have the right to remove the copyright declaration from the files https://github.com/NotepadFree/NotepadFree/commit/e7a014388ab16ef07d412d0b0c1aa073ccb605dc. 
You need to put back the copyright declaration of "Copyright (C)2021 Don HO <don.h@free.fr>" to honor the original work of the author. 

Please take some time to learn about this free course (开发人员合规基础课程). https://training.linuxfoundation.cn/course/4
It tells you what kind of thing you can do and what kind of thing you cannot do when you write code in the Open Source world.

You can not change the source file license header and the License file, especially on the copyright part, as you are not the original author. If you made significant changes to the source file, you could add your copyright to the license header.

**Comment by SuperH-0630** [comment]
如果我想通过声明知道Notepad++哪一部分来自Scintilla，我应该怎么做呢？

**Comment by SongZihuan** [comment]
完成

**Comment by WillemJiang** [comment]
The last change you made is not enough. Please check out my comments  https://github.com/NotepadFree/NotepadFree/commit/e7a014388ab16ef07d412d0b0c1aa073ccb605dc. 

You should not remove the Copyright statement from the original author.

**Comment by WillemJiang** [comment]
You can find more information about how to apply the license header in ASF [here](https://apache.org/legal/src-headers.html).
There are some differences if you do it outside the ASF, but it gives you a general idea of how to declare your work in a source file. In this way, people can tell which part of the work is your original work.
