### ISSUE TITLE
虽然我不会使用notepad++及其衍生的垃圾，但是我支持一切恶心台独的正义之举

### ISSUE THREAD

**Issue by wuqingze** [NotepadFree/NotepadFree#12]
如上

**Comment by black-wolfie** [comment]
软件源代码当然容易抄，但是创新精神抄袭不来。
国产28nm光刻机难产，海峡对岸却已经进军2nm。

竞争不赢也许会破罐子破摔发动战争。不过记住，清朝输了甲午，政权就垮咯。

**Comment by uxiew** [comment]
不推荐 notepad++；如果也不用 vscode，但会经常打开代码看看，那么推荐使用轻量级的 [Notepad3](https://github.com/rizonesoft/Notepad3) ！当然 vim 也绝对不错！

**Comment by Jimmy20220531** [comment]
> 软件源代码当然容易抄，但是创新精神抄袭不来。 国产28nm光刻机难产，海峡对岸却已经进军2nm。
> 
> 竞争不赢也许会破罐子破摔发动战争。不过记住，清朝输了甲午，政权就垮咯。

海峡对岸的光刻机能自己造不？不懂就别瞎BB，连基本概念都混淆。
