### ISSUE TITLE
一起来开发墨干编辑器吧

### ISSUE THREAD

**Issue by darcy-shen** [NotepadFree/NotepadFree#9]
https://github.com/XmacsLabs/mogan

没必要在Notepad++上浪费时间。

**Comment by SuperH-0630** [comment]
我觉得你的建议不错，请问他有更多的文档吗？

**Comment by darcy-shen** [comment]
文档是内置的，tm格式的。你下载软件并安装，可以在`帮助->墨客星球`看到很多文档。

我们每两周会有一次视频会议，开发者和用户会在视频会议中交流。

**Comment by darcy-shen** [comment]
墨干编辑器基于GNU TeXmacs，目前在代码编辑方面还比较弱。它的特色主要在科技编辑（数学公式）。

不知道你看中Notepad++哪一点，我没有用过Notepad++。如果是代码编辑的话，我们可以在墨干中做一个比Notepad++更好的。

**Comment by SuperH-0630** [comment]
好的，我下载了解一下。我看重Notepad++好编译，我本人不用Notepad++。我喜欢的事情是开发语言，所以我也想研究编辑器来给我的语言做IDE支持。

**Comment by xieyudi** [comment]
中国人就会满世界抄

**Comment by SuperH-0630** [comment]
NPP同意我抄了我为什么不能抄

**Comment by xieyudi** [comment]
就是中国人满世界到处抄的意思。
中国人以为全世界都是中国人😓

**Comment by PhDLuffy** [comment]
> NPP同意我抄了我为什么不能抄

npp这坨屎没有必要抄，抄的再好也是一坨屎。

有更好的轻量编辑器可以用，有更好的编辑平台可以二次开发，没有必要浪费时间和精力放到一坨屎上面。

大家也没必要吃这用清水简单冲洗的一坨屎。

**Comment by ice1000** [comment]
> 好的，我下载了解一下。我看重Notepad++好编译，我本人不用Notepad++。我喜欢的事情是开发语言，所以我也想研究编辑器来给我的语言做IDE支持。

大佬打算做什么样的语言？我现在有一个团队在开发 [Aya](https://github.com/aya-prover/aya-dev) 语言，我也想做自包含的 IDE，可直到现在都没想好技术选型。

**Comment by ice1000** [comment]
大佬，我看了你知乎，上面有 HMCL 的问题。我们团队成员之一 Glavo 也是 HMCL 的贡献者，世界真小！

**Comment by wqlxx** [comment]
> 中国人就会满世界抄。自己政府都不让翻墙上外网了还满世界抄。

我摊牌了，你的DNA是抄了我和你妈的一人一半的。抱歉大家，给世界留下这个杂种，都是他妈逼的。

**Comment by xieyudi** [comment]
> > 中国人就会满世界抄。自己政府都不让翻墙上外网了还满世界抄。
> 
> 我摊牌了，你的DNA是抄了我和你妈的一人一半的。抱歉大家，给世界留下这个杂种，都是他妈逼的。

翻墙货请在给你待的地方待好。谢谢。

**Comment by da-liii** [comment]
@SuperH-0630 TeXmacs里面有一门样式语言，然后使用的S7 Scheme。这样就有两门有趣的语言了。

后面我会设计一门墨干语言，搭配墨干编辑器使用。一门支持数学公式的结构化编程语言！

**Comment by da-liii** [comment]
https://github.com/XmacsLabs/mogan-lang

可以关注一下，后续我们会慢慢把这门语言的Spec先写出来。

**Comment by wqlxx** [comment]
> > > 中国人就会满世界抄。自己政府都不让翻墙上外网了还满世界抄。
> > 
> > 
> > 我摊牌了，你的DNA是抄了我和你妈的一人一半的。抱歉大家，给世界留下这个杂种，都是他妈逼的。
> 
> 翻墙货请在给你待的地方待好。谢谢。

贱货在你的贱地呆好了。不用谢。

**Comment by xieyudi** [comment]
> > > > 中国人就会满世界抄。自己政府都不让翻墙上外网了还满世界抄。
> > > 
> > > 
> > > 我摊牌了，你的DNA是抄了我和你妈的一人一半的。抱歉大家，给世界留下这个杂种，都是他妈逼的。
> > 
> > 
> > 翻墙货请在给你待的地方待好。谢谢。
> 
> 贱货在你的贱地呆好了。不用谢。

贱地方不让你们中国人死皮赖脸爬过来翻墙上还非要上，因为你们中国人天生比较差什么都做不出来，只能到处偷😓
